# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Give_away',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Station_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='NULL', max_length=64)),
                ('name', models.CharField(default='NULL', max_length=32)),
                ('number', models.CharField(default='0', max_length=16)),
            ],
        ),
    ]
