# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='station_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.TextField(default='./pics/empty_img')),
                ('name', models.CharField(default='NULL', max_length=32)),
            ],
        ),
    ]
